inherit_from: base.yaml
experiment:
    experiment_name: mug_on_rack_multi_nosc
    num_iterations: 50
    meshcat_on: True
    pybullet_viz: False
    parent_class: syn_rack_med
    child_class: mug
    is_parent_shapenet_obj: False
    is_child_shapenet_obj: True
    n_parent_instances: 4
    parent_crop: True
    show_floating_hand_meshcat: False
    use_floating_hand_execution: True
    eval:
        # pose_refine_model_name: mug_on_rack_multi_refine_pose_only_nsmglobal_1q_diff_steps_timestep_anneal_crop_interp_large_5_more_precise_sampling_rpdiff_edit
        # success_model_name: mug_on_rack_multi_success_only_yaw_rot_aug_pos_weight_1-0_default_pn_nsmglobal_arch
        pose_refine_model_name: quickstart_weights/mug_rack_multi_pose_diff_varying_crop_qs
        success_model_name: quickstart_weights/mug_rack_multi_success_cls_qs
        rand_mesh_scale: False
        parent_load_pose_type: random_upright
        child_load_pose_type: random_upright
        inference_method: multistep_regression_scene_combine_succ_cls 
        return_rand: False
        with_coll: False
        n_refine_iters: 50
        init_orig_ori: False
        init_k_val: 32
        no_success_classifier: False
        variable_size_crop: True
        timestep_emb_decay_factor: 20  # larger values emphasize quicker decay toward using timestep 0 (more precise, more local)
        add_per_iter_noise: True
        per_iter_noise_kwargs:
            rot:
                angle_deg: 20 
                rate: 6.5
            trans:
                trans_dist: 0.03 
                rate: 5.5

environment:
    n_cameras: 4
    cameras:
        yaw_angles: [45.0, 135.0, 225.0, 315.0]
        distance: 1.0
        pitch: -25.0
        focus_pt: [0.5, 0.0, 1.4]
        single_focus_pt: True
        single_pitch: True

