experiment:
    experiment_name: smoketest
    logdir: rpdiff # relation_policy_cachedir
    resume_iter: 0
    resume: False
    meshcat_on: True
    debug: False
    eval_data_dir: eval_data
    num_iterations: 100
    start_iteration: 0
    pybullet_viz: False
    pybullet_server: True
    parent_class:
    child_class:
    is_parent_shapenet_obj: 
    is_child_shapenet_obj: 
    n_parent_instances: 1
    parent_crop: True
    use_floating_hand_execution: False
    show_floating_hand_meshcat: False
    upright_ori_diff_thresh_deg: 15 
    load_pose_regression: True
    load_success_classifier: True
    load_coarse_aff: False
    eval:
        feat_enc_model_name:
        voxel_aff_model_name:
        pose_refine_model_name:
        success_model_name:
        voxel_aff_model_name_full:
        pose_refine_model_name_full:
        success_model_name_full:
        rand_mesh_scale: False
        only_test_ids: True
        parent_load_pose_type: 'random_upright'
        child_load_pose_type: 'random_upright'
        inference_method: null  # multistep_regression_scene_combine_succ_cls, scatter_multistep_regression_scene_combine_succ_cls
        return_rand: False
        with_coll: False
        n_refine_iters:
        load_full_pcd: False
        run_affordance: False
        init_parent_mean_pos: False
        init_orig_ori: False
        init_k_val: 10
        no_success_classifier: False
        refine_anneal: False
        multi_aff_rot: False
        variable_size_crop: False
        timestep_emb_decay_factor: 20  # larger values emphasize quicker decay toward using timestep 0 (more precise, more local)
        add_per_iter_noise: False
        per_iter_noise_kwargs:
            rot:
                angle_deg: 20 
                rate: 6.5
            trans:
                trans_dist: 0.03 
                rate: 5.5

baseline_experiment:
    rndf:
        crop_parent: False
        num_sep_opts: 1
        parent_model_path:
        child_model_path:
        opt_visualize: True
        opt_iterations: 500
        optimizer:
            SHAPE_PCD_PTS_N: 1500
            QUERY_PCD_PTS_N: 500

environment:
    table_z: 1.2
    table_ori: [0.0, 0.0, 0.7071067811865475, 0.7071067811865476]
    table_pos: [0.5, 0.0, 0.0]
    mesh_scale_default: 0.3
    mesh_scale_high: 0.4
    mesh_scale_low: 0.2
    obj_sample_x_high_low: [0.4, 0.5]
    obj_sample_y_high_low: [-0.4, 0.4]
    obj_sample_place_x_dist: 0.05  
    obj_sample_place_y_dist: 0.25  
    n_cameras: 3 
    cameras:
        yaw_angles: 330.0, 30.0, 90
        distance_set:
        distance: 1.0
        pitch: 
        pitch_set: [-10.0, -10.0, -35.0]
        focus_pt:
        focus_pt_set: [[0.5, 0.5, 1.4], [0.5, 0.5, 1.4], [0.35, 0.0, 1.1]]
        single_focus_pt: False
        single_pitch: False
        single_distance: True

objects:
    default_upright_euler: [0, 0, 0]
    categories:
        mug: 
            upright_euler: [1.570796, 0, 0]
            mesh_dir: mug_centered_obj_normalized
            scale_hl: [0.35, 0.25]
            scale_default: 0.3
        syn_rack_easy:
            upright_euler: 
            mesh_dir: syn_racks_easy_obj
            scale_hl: [0.35, 0.25]
            scale_default: 0.3
        syn_rack_med: 
            upright_euler: 
            mesh_dir: syn_rack_med
            scale_hl: [0.35, 0.25]
            scale_default: 0.3
        syn_rack_hard:
            upright_euler: 
            mesh_dir: syn_racks_hard_obj
            scale_hl: [0.35, 0.25]
            scale_default: 0.3
        syn_bookshelf:
            upright_euler: 
            mesh_dir: syn_bookshelf_obj_unnormalized
            scale_hl: [1.005, 0.995]
            scale_default: 1.0
        syn_book: 
            upright_euler: 
            mesh_dir: syn_books_obj
            scale_hl: [1.005, 0.995]
            scale_default: 1.0
        syn_cabinet:
            upright_euler: 
            mesh_dir: syn_can_cabinet_obj_unnormalized
            scale_hl: [1.005, 0.995]
            scale_default: 1.0
        syn_cabinet_packed_uniform:
            upright_euler: 
            mesh_dir: syn_can_cabinet_packed_nonuniform_unnormalized
            scale_hl: [1.005, 0.995]
            scale_default: 1.0
        syn_cabinet_packed_nonuniform:
            upright_euler: 
            mesh_dir: syn_can_cabinet_packed_uniform_unnormalized
            scale_hl: [1.005, 0.995]
            scale_default: 1.0
        syn_can:
            upright_euler: 
            mesh_dir: syn_cans_obj
            scale_hl: [1.005, 0.995]
            scale_default: 1.0
        
data:
    dataset_path: null  # set me to specify dataset folder
    data_root: demo_aug
    split: test_train
    load_into_memory: True
    load_full_pcd: False
    parent_mesh_dir:
    child_mesh_dir:
    parent_crop: True
    rot_aug: null # None, yaw, rot
    apply_pcd_aug: False
    pcd_aug_prob: 0.0
    shape_pcd_n: 2048
    custom_split_fname: null
    rot_grid_samples: 1.0e+4
    rot_grid_bins: null  # gets set when we actually compute the grid
    debug_viz: False
    voxel_grid:
        reso_grid: 32
        padding: 0.1
    pose_perturb:
        rot_scale_deg: 360
        trans_scale: 12
        small_rot_scale_deg: 30
        small_trans_scale: 0.04
        use_small_rot_scale: False
        use_small_trans_scale: False
        rot_min:
        trans_min:
        parent_cent_offset_scale: 0.01
    coarse_aff:
        shape_pcd_n: 
        scene_mean: [0.35, 0.0, 0.0]
        scene_extents: [0.7, 1.2, 0.0]
        aug:
            rot_aug:
            apply_pcd_aug: 
            pcd_aug_prob: 
    refine_pose:
        shape_pcd_n: 
        parent_crop: True
        parent_crop_same_n: True
        crop_box_length: 0.18
        aug:
            rot_aug:
            apply_pcd_aug: 
            pcd_aug_prob: 
    success:
        shape_pcd_n: 
        success_rot_scale_deg: 5
        success_trans_scale: 0.005
        fail_rot_scale_deg: 180
        fail_trans_scale: 0.05
        fail_rot_min_deg: 5
        fail_trans_min: 0.005
        success_fail_prob: 0.5
        aug:
            rot_aug:
            apply_pcd_aug: 
            pcd_aug_prob: 

model:
    coarse_aff:
        type: cnn
        feat_dim: 5
    refine_pose:
        type: transformer # nsm_transformer, transformer, tranfsormer_mq, pointnet, cnn    
        feat_dim: 3
        model_kwargs:
            nsm_transformer:
                n_queries: 1
                use_timestep_emb: False
                max_timestep:  
                timestep_pool_method: meanpool  # meanpool, concat
    success:
        type: transformer
        feat_dim: 3
    nsm_transformer:
        n_blocks: 4
        n_heads: 1
        drop_p: 0.0
        n_pts: 1024
        pn_pts: 
        cn_pts: 
        hidden_dim: 256
        pooling: max
        bidir: False
    nsm_transformer_cvae:
        n_blocks: 4
        n_heads: 1
        drop_p: 0.0
        n_pts: 1024
        pn_pts: 
        cn_pts: 
        hidden_dim: 256
        pooling: max
        bidir: False
        residual_latent: False
        residual_tf_enc: False
        latent_pool_method: meanpool  # meanpool, concat
        tf_pool_method: meanpool  # meanpool, concat
    nsm_transformer_mq:
        n_blocks: 4
        n_heads: 1
        drop_p: 0.0
        n_pts: 1024
        pn_pts: 
        cn_pts: 
        hidden_dim: 256
        pooling: max
        n_queries: 2
        return_intermediate: True
    transformer:
        n_blocks: 4
        n_heads: 1
        drop_p: 0.1
        n_pts: 1024
        hidden_dim: 256
    transformer_mq:
        n_blocks: 4
        n_heads: 1
        drop_p: 0.1
        n_pts: 1024
        hidden_dim: 256
        n_queries: 2
    pointnet:
        n_pts: 1024
        hidden_dim: 256
    cnn:  # regular cnn
        local_coord: True
        # encoder: pointnet_local_pool
        c_dim: 32
        # encoder_kwargs:
        hidden_dim: 32  
        # plane_type: ['xz', 'xy', 'yz', 'grid']
        plane_type: ['grid']
        # grid_resolution: 32
        unet3d: True
        unet3d_kwargs:
            num_levels: 3
            f_maps: 32
            in_channels: 32  
            out_channels: 32  
            plane_resolution: 128 
        unet: False
        unet_kwargs:
            depth: 5
            merge_mode: concat
            start_filts: 32
    minkcnn:  # minkowski engine
    feat_encoder:
        type: null
        parent_encoder_path: null
        child_encoder_path: null
        joint_encoder_path: null
