inherit_from: base.yaml

experiment:
    experiment_name: mug_rack_multi_partial_view_test
    debug: False
    num_iterations: 100
    parent_class: syn_rack_hard
    child_class: mug
    is_child_shapenet_obj: true
    task_name: mug_on_rack_multi
    n_parent_instances: 3
    demo:
        vary_about_peg: True

environment:
    n_cameras: 2 
    cameras:
        # yaw_angles: [330.0, 30.0]
        yaw_angles: [345.0, 15.0]
        distance_set:
        distance: 1.5
        # distance: 1.0
        pitch: 
        pitch_set: [-10.0, -10.0]
        focus_pt:
        focus_pt_set: [[0.5, 0.5, 1.1], [0.5, 0.5, 1.1]]
        single_focus_pt: False
        single_pitch: False
        single_distance: True

